# Generated by Django 4.2.20 on 2025-03-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
    ]
