# Generated by Django 4.2.20 on 2025-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_parametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='periodo',
            field=models.CharField(max_length=29),
        ),
    ]
