# Generated by Django 4.2.20 on 2025-03-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mensalista_valor_mes_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmensalista',
            old_name='data_pto',
            new_name='data_pgto',
        ),
    ]
